DROP TABLE MOVIES;
CREATE TABLE MOVIES (
	id INT NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    release_date VARCHAR(100) NOT NULL,
    duration INT NOT NULL,
    score INT NOT NULL
);

DROP TABLE GENRES;
CREATE TABLE GENRES (
	id INT NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

DROP TABLE MOVIE_GENRES;
CREATE TABLE MOVIE_GENRES (
	movie_id VARCHAR(5) NOT NULL,
    genre_id VARCHAR(3) NOT NULL,
    PRIMARY KEY(movie_id, genre_id)
);

DROP TABLE ACTORS;
CREATE TABLE ACTORS (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    birth_date VARCHAR(100) NOT NULL,
    height INT NOT NULL
);

DROP TABLE DIRECTORS;
CREATE TABLE DIRECTORS (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    birth_date VARCHAR(100) NOT NULL,
    height INT NOT NULL
);